### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by hunar1997** [hunar1997/BitmapLogicSimulatorClone#1]
## Here are the issues that should be solved
- [ ] Can't load non-square images
- [ ] Clicking outside image crashes it
- [ ] Make the simulation faster and less resource heavy
- [ ] Dont update the gates that are not updated
- [ ] Change the (setPixel) function to something faster
- [ ] Circuits that have wires touching boundary crashes
- [ ] The circuit flickers some times
- [ ] Load AND SHOW colourfull circuits instead of showing as B&W
